# Generated by Django 5.2.17 on 2026-08-16 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('weekday', models.SmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday. Leave empty to apply to every day.', null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='0 means you skip this slot by default.', validators=[django.core.validators.MaxValueValidator(20)])),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', 'slot'],
            },
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='price',
        ),
        migrations.AddField(
            model_name='mealentry',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
