# Generated by Django 5.2.17 on 2026-08-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealplan_remove_mealentry_price_mealentry_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='weekday',
        ),
    ]
